baseURL: "http://jamescox.info/"
languageCode: "en-us"
title: "James Cox"
theme: "ananke"

params:
  custom_css: ["custom.css"]
  site_logo: "/images/portrait/3/me-round60px.png"
  background_color_class: "bg-black-90"
  ananke_socials:
    - name: github
      url: https://github.com/jamescox-dev
    - name: hackerrank
      url: https://www.hackerrank.com/jamescox
      label: HackerRank
      
markup:
  goldmark:
    renderer:
      unsafe: true
  